import React, { useEffect, useRef, useState } from 'react';
import { Animated, Easing, Image, ScrollView, StyleSheet, View } from 'react-native';
import { ActivityIndicator, Button, Card, Chip, Text, useTheme } from 'react-native-paper';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';

import { useSettingsStore, useUserStore } from '../../store';
import { LlmService } from '../../services/llm';
import { avatarUrl } from './avatarUtils';
import type { OnboardingStackParamList } from './types';

type Props = NativeStackScreenProps<OnboardingStackParamList, 'Tour'>;

const FALLBACK_TOUR = `Hey there — I'm the little language model that lives on your phone now. Nice to meet you. 👋

Here's the deal with AI Social: every post in your feed is something I (or a sibling model) made up just now, just for you. The accounts aren't real. The hot takes aren't real. The guy who insists pineapple belongs on pizza is, regrettably, still not real.

You can pull to refresh for a brand-new feed, tap a post to see fictional comments roll in, and use Compose to seed a topic and watch a draft appear. Everything happens locally — no servers, no tracking, no internet required after this.

Treat it like a daydream you can scroll through. Have fun with it.`;

function buildTourPrompt(name: string, handle: string, bio: string): string {
  const lines = [
    `You are the on-device language model that powers an app called "AI Social".`,
    `The user just finished onboarding. Their display name is "${name}", handle "@${handle}".`,
    bio ? `Their one-line bio is: "${bio}".` : ``,
    ``,
    `Write a short, warm, slightly playful welcome message (about 120-180 words, 2-3 short paragraphs)`,
    `that explains what AI Social is and how it works. Cover these points naturally, without a bulleted list:`,
    `  - Every post and comment in the feed is fiction generated by a local model running on their phone.`,
    `  - Nothing is uploaded; there are no real accounts, no servers, no ads.`,
    `  - They can refresh the feed for new posts, tap a post for fictional comments, and use Compose to draft posts.`,
    `  - You are that local model. Speak in first person ("I").`,
    ``,
    `Address them by name once, naturally. Be a little funny but not cringe. End with one short sentence inviting them in.`,
    `Return plain text only — no markdown, no headings, no quotes around the response.`,
  ];
  return lines.filter(Boolean).join('\n');
}

export const TourScreen = ({ navigation }: Props) => {
  const theme = useTheme();
  const settings = useSettingsStore();
  const setOnboardingComplete = useUserStore((s) => s.setOnboardingComplete);
  const profile = useUserStore((s) => s.profile);

  const [tour, setTour] = useState<string>('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [usedFallback, setUsedFallback] = useState(false);

  const fade = useRef(new Animated.Value(0)).current;
  const dot1 = useRef(new Animated.Value(0)).current;
  const dot2 = useRef(new Animated.Value(0)).current;
  const dot3 = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    if (!loading) return;
    const seq = (v: Animated.Value, delay: number) =>
      Animated.loop(
        Animated.sequence([
          Animated.timing(v, { toValue: 1, duration: 500, delay, useNativeDriver: true, easing: Easing.inOut(Easing.ease) }),
          Animated.timing(v, { toValue: 0, duration: 500, useNativeDriver: true, easing: Easing.inOut(Easing.ease) }),
        ]),
      );
    const a = seq(dot1, 0);
    const b = seq(dot2, 150);
    const c = seq(dot3, 300);
    a.start(); b.start(); c.start();
    return () => { a.stop(); b.stop(); c.stop(); };
  }, [loading, dot1, dot2, dot3]);

  useEffect(() => {
    let cancelled = false;
    const run = async () => {
      setLoading(true);
      setError(null);
      try {
        const prompt = buildTourPrompt(profile.name, profile.handle, profile.bio);
        const text = await LlmService.generateText(settings, prompt);
        if (cancelled) return;
        setTour(text.trim());
        Animated.timing(fade, { toValue: 1, duration: 600, useNativeDriver: true }).start();
      } catch (e) {
        if (cancelled) return;
        setError(e instanceof Error ? e.message : String(e));
        setUsedFallback(true);
        const personal = `Hey ${profile.name || 'friend'} — `;
        setTour(personal + FALLBACK_TOUR);
        Animated.timing(fade, { toValue: 1, duration: 600, useNativeDriver: true }).start();
      } finally {
        if (!cancelled) setLoading(false);
      }
    };
    run();
    return () => { cancelled = true; };
  }, []);

  const finish = () => {
    setOnboardingComplete(true);
  };

  const dotStyle = (v: Animated.Value) => ({
    opacity: v.interpolate({ inputRange: [0, 1], outputRange: [0.25, 1] }),
    transform: [{ translateY: v.interpolate({ inputRange: [0, 1], outputRange: [0, -3] }) }],
  });

  return (
    <ScrollView
      style={[styles.scroll, { backgroundColor: theme.colors.background }]}
      contentContainerStyle={styles.content}
    >
      <Text variant="labelMedium" style={{ color: theme.colors.primary, marginBottom: 4 }}>
        STEP 3 OF 3
      </Text>
      <Text variant="headlineMedium" style={styles.title}>
        Say hi to your model
      </Text>
      <Text variant="bodyMedium" style={[styles.blurb, { color: theme.colors.onSurfaceVariant }]}>
        It's writing you a personal welcome — live, on your phone, with no internet.
      </Text>

      <Card style={styles.card}>
        <Card.Content>
          <View style={styles.row}>
            {profile.avatarSeed ? (
              <Image source={{ uri: avatarUrl(profile.avatarSeed, 96) }} style={styles.avatar} />
            ) : (
              <View style={[styles.avatar, { backgroundColor: theme.colors.surfaceVariant }]} />
            )}
            <View style={{ flex: 1 }}>
              <Text variant="titleSmall" style={{ fontWeight: '700' }}>
                {profile.name || 'You'}
              </Text>
              <Text variant="bodySmall" style={{ color: theme.colors.onSurfaceVariant }}>
                @{profile.handle || 'newuser'}
              </Text>
            </View>
            <Chip compact icon="cellphone">on-device</Chip>
          </View>

          <View style={styles.bubble}>
            {loading ? (
              <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
                <ActivityIndicator size="small" />
                <Text variant="bodyMedium" style={{ color: theme.colors.onSurfaceVariant }}>
                  Thinking
                </Text>
                <Animated.Text style={[{ fontSize: 18 }, dotStyle(dot1)]}>·</Animated.Text>
                <Animated.Text style={[{ fontSize: 18 }, dotStyle(dot2)]}>·</Animated.Text>
                <Animated.Text style={[{ fontSize: 18 }, dotStyle(dot3)]}>·</Animated.Text>
              </View>
            ) : (
              <Animated.View style={{ opacity: fade }}>
                <Text variant="bodyMedium" style={{ lineHeight: 22 }}>
                  {tour}
                </Text>
                {usedFallback && (
                  <Text variant="labelSmall" style={{ marginTop: 10, opacity: 0.6, fontStyle: 'italic' }}>
                    (Couldn't reach the local model just now, so this is the canned version.{error ? ` Reason: ${error}` : ''})
                  </Text>
                )}
              </Animated.View>
            )}
          </View>
        </Card.Content>
      </Card>

      <Button
        mode="contained"
        onPress={finish}
        disabled={loading}
        style={styles.cta}
        contentStyle={{ paddingVertical: 6 }}
        icon="check"
      >
        Open my feed
      </Button>
      <Button mode="text" onPress={() => navigation.navigate('Welcome')} disabled={loading} style={{ marginTop: 4 }}>
        Start over
      </Button>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  scroll: { flex: 1 },
  content: { padding: 24, paddingBottom: 60 },
  title: { fontWeight: '700', marginBottom: 6 },
  blurb: { marginBottom: 18 },
  card: { marginBottom: 18 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 14 },
  avatar: { width: 48, height: 48, borderRadius: 24 },
  bubble: {
    backgroundColor: 'rgba(127,127,127,0.08)',
    borderRadius: 14,
    padding: 14,
    minHeight: 90,
  },
  cta: { borderRadius: 999, marginTop: 8 },
});
