import React, { useCallback } from 'react';
import { ScrollView, StyleSheet, View, Linking, Alert } from 'react-native';
import { Text, Button, useTheme } from 'react-native-paper';
import Constants from 'expo-constants';
import { APP_LINKS } from '../appLinks';

const openUrl = async (url: string, label: string) => {
  try {
    const supported = await Linking.canOpenURL(url);
    if (!supported) {
      Alert.alert('Cannot open link', `No app can open ${label}.`);
      return;
    }
    await Linking.openURL(url);
  } catch {
    Alert.alert('Error', `Could not open ${label}.`);
  }
};

export const AboutScreen = () => {
  const theme = useTheme();
  const version =
    Constants.expoConfig?.version ?? Constants.nativeAppVersion ?? '-';

  const onGithub = useCallback(() => openUrl(APP_LINKS.github, 'GitHub'), []);
  const onWebsite = useCallback(() => openUrl(APP_LINKS.website, 'Website'), []);
  const onCoffee = useCallback(() => openUrl(APP_LINKS.buyMeACoffee, 'Buy Me a Coffee'), []);

  return (
    <ScrollView
      style={[styles.scroll, { backgroundColor: theme.colors.background }]}
      contentContainerStyle={styles.content}
    >
      <Text variant="headlineSmall" style={styles.title}>
        AISocial
      </Text>
      <Text variant="bodyMedium" style={[styles.body, { color: theme.colors.onSurfaceVariant }]}>
        AISocial is a small social-style feed where posts are generated by an LLM. You can run models
        on-device (Android with a MediaPipe `.task` model) or connect to your own Ollama server, with
        a hybrid mode that prefers local inference and can fall back to remote when you allow it.
      </Text>
      <Text variant="bodyMedium" style={[styles.body, { color: theme.colors.onSurfaceVariant }]}>
        Compose new posts, browse the feed, download models, and tune behavior from Settings. Nothing
        is shipped with a fixed cloud backend; you choose where inference runs.
      </Text>
      <Text variant="labelLarge" style={styles.version}>
        Version {version}
      </Text>

      <View style={styles.actions}>
        <Button mode="contained-tonal" icon="github" onPress={onGithub} style={styles.btn}>
          Source on GitHub
        </Button>
        <Button mode="outlined" icon="web" onPress={onWebsite} style={styles.btn}>
          Project website
        </Button>
        <Button mode="contained" icon="heart" onPress={onCoffee} style={styles.btn}>
          Support on Buy Me a Coffee
        </Button>
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  scroll: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingBottom: 40,
  },
  title: {
    marginBottom: 12,
  },
  body: {
    marginBottom: 14,
    lineHeight: 22,
  },
  version: {
    marginTop: 8,
    marginBottom: 24,
    opacity: 0.85,
  },
  actions: {
    gap: 12,
  },
  btn: {
    alignSelf: 'stretch',
  },
});